---
title: "Estudos Iniciais em Simulação de Dados"
author: "Ricardo da Fonseca"
format: 
  html:
    number-sections: true
editor: visual
lang: pt-BR
---

## Introdução

1.  Por que a simulação de dados é importante?

    1.  redução de custos;

    2.  exploração do desconhecido;

    3.  auxílio na tomada de decisões.

2.  Por que a simulação de dados é importante na graduação?

    1.  Estudos mais aprofundados;

    2.  Desenvolvimento de capacidade de interpretação.

3.  Simulação de Monte Carlo

## Introdução ao R

Nessa seção apresentarei alguns comandos básicos para R que usaremos durante nossos estudos.

As funções apresentadas nessa seção serão:

- *summary*

- *data.frame*

- *c*

- *list*

- *rnorm*

- *sample*

- *seed*

## Introdução ao Rmarkdown

Falar sobre os comandos:

- Headings 1, 2, 3, ...

- itálico

- negrito

## Distribuições de Probabilidade

1.  Normal
2.  Gamma
3.  F
4.  t
5.  Qui-quadrado

## Simulações (Nível 1): Dados Experimentais de de Coleta Única

### DIC

Para simularmos dados de um Delineamento Inteiramento Casualizado (DIC) devemos definir o modelo e a distribuição de probabilidade associada a cada efeito aleatório.

O modelo utilizado no DIC é:

$$y_{ij} = \mu + t_i + e_{ij}$$

em que:

$y_{ij} =$ j-ésima observação do i-ésimo tratamento;

$\mu =$ média da variável resposta;

$t_i =$ efeito do i-ésimo tratamento;

$e_{ij} =$ erro associado à j-ésima observação do i-ésimo tratamento;

São efeitos aleatórios no modelo: $y$ e $e$; $\mu$ e $t$ são considerados efeitos fixos. Portanto, precisamos definir a distribuição dos efeitos aleatórios. A distribuição de $y$ fica definida pela distribuição assumida para $e$, uma vez que é uma combinação linear desse efeito. Assim, se assumirmos que $e$ tem distribuição normal, também o terá $y$.

Pode-se pensar em dividir a resolução do problema de simular os dados em três partes:

1.  Simular os efeitos aleatórios;
2.  Simular os efeitos fixos;
3.  Calcular a variável resposta ou dependente.

#### Simular os efeitos aleatórios

Propriedade da Reprodutibilidade:

Se $X_1\sim N\left(\mu_1, \sigma_1^2\right)$ e $X_2\sim N\left(\mu_2, \sigma_2^2\right)$

Então para quaisquer constantes *a* e *b*:

$Y = aX_1 + bX_2 \sim N\left(a\mu_1 + b\mu_2, (a\sigma_1)^2 + (b\sigma_2)^2\right)$

Assim, é fácil de ver que se $e\sim N\left(0, \sigma^2_e\right)$, então $Y\sim N\left(\mu, \sigma_e^2\right)$

Para iniciarmos a simulação dos dados precisamos definir também quantos níveis serão considerados para o efeito fixo de tratamento $\left(t\right)$.

1.  DBC

2.  DQL

3.  Experimentos Fatoriais

4.  Coleta (definir modelo)

## Simulações (Nível 2): Dados Experimentais e de Coleta Única com n Características Correlacionados

1.  Decomposição de Cholesky
2.  Análise de regressão (Simular dados via equação de regressão e adicionar os resíduos. Como simular especificando uma correlação ou R2 específico?)

## Simulações (Nível 3): Dados Coletados por n Gerações

1.  Envolve a definição de progenitores
2.  Simular à partir de um pedigree?

## Simulações (Nível 4): Dados Genéticos Coletados por n Gerações com Simulação de Genes ou QTLs

1.  Gene dropping, forward simulation
2.  Geração de genoma

## Simulações (Nível 5): Dados Genéticos Coletados por n Gerações com Simulação de Genes ou QTLs e Características Correlacionadas.

1.  Geração de genoma
2.  Escolha de reprodutores

## Simulações (Nível 6): Dados Genômicos

1.  Linkage desiquilibrium
2.  Equilíbrio mutação - deriva genética
